#!/usr/bin/env python
"""
Sweep script to test different aug_mult configurations for CIFAR10 training
using parallel_audit_model.py (multi-GPU with torchrun on SLURM).

Usage:
    python sweep_aug_mult_parallel.py              # Generate SLURM script
    python sweep_aug_mult_parallel.py --run        # Run directly (single node)
"""
import subprocess
import sys
import os
import argparse
from datetime import datetime

# =============================================================================
# CONFIGURATION - Edit these values to customize the sweep
# =============================================================================

AUG_MULT_VALUES = [1, 2, 4, 8, 16]
RUN_NON_PRIVATE = True  # Run one experiment without DP (epsilon=None)

# Training parameters
MODEL_NAME = "cnn"
N_REPS = 2
N_EPOCHS = 100
LR = 1.33e-4
BATCH_SIZE = 4000
BLOCK_SIZE = 500
EPSILON = 10.0
DELTA = 1e-5
MAX_GRAD_NORM = 1.0
SEED = 0
OUT_DIR = "sweep_results_parallel"

# Distributed training parameters
NPROC_PER_NODE = 1  # Number of GPUs per node

# Optional parameters (set to None to disable)
MAX_PHYSICAL_BATCH_SIZE = 3000
EARLY_STOPPING = None
FIT_WORLD_ONLY = "in"

# =============================================================================


def get_max_physical_batch_size(aug_mult):
    """Get max physical batch size based on aug_mult."""
    if aug_mult <= 4:
        return 4000
    elif aug_mult == 8:
        return 3000
    else:  # aug_mult >= 16
        return 1500


def build_torchrun_cmd(aug_mult, epsilon=EPSILON, run_name=None, n_epochs=N_EPOCHS, 
                       batch_size=BATCH_SIZE, model_name=MODEL_NAME, max_grad_norm=MAX_GRAD_NORM):
    """Build the torchrun command string for parallel_audit_model.py."""
    if run_name is None:
        run_name = f"aug_mult_{aug_mult}"
    out_folder = f"{OUT_DIR}/{run_name}"
    
    args = [
        f"--data_name cifar10",
        f"--model_name {model_name}",
        f"--aug_mult {aug_mult}",
        f"--n_reps {N_REPS}",
        f"--n_epochs {n_epochs}",
        f"--lr {LR}",
        f"--batch_size {batch_size}",
        f"--block_size {BLOCK_SIZE}",
        f"--seed {SEED}",
        f"--out {out_folder}",
        f"--fixed_init",
    ]
    
    # Add privacy parameters only if epsilon is set
    if epsilon is not None:
        args.append(f"--epsilon {epsilon}")
        args.append(f"--delta {DELTA}")
        args.append(f"--max_grad_norm {max_grad_norm}")
    else:
        # Non-private training: disable gradient clipping
        args.append("--max_grad_norm -1")
    
    max_physical_batch_size = get_max_physical_batch_size(aug_mult)
    args.append(f"--max_physical_batch_size {max_physical_batch_size}")
    
    if FIT_WORLD_ONLY is not None:
        args.append(f"--fit_world_only {FIT_WORLD_ONLY}")
    
    return run_name, " \\\n         ".join(args)


def generate_slurm_script():
    """Generate a SLURM script with all experiments."""
    
    experiments = []
    
    # Non-private baseline
    if RUN_NON_PRIVATE:
        experiments.append(build_torchrun_cmd(aug_mult=1, epsilon=None, run_name="non_private"))
    
    # aug_mult sweep with DP
    for aug_mult in AUG_MULT_VALUES:
        experiments.append(build_torchrun_cmd(aug_mult))
    
    # Additional experiments
    experiments.append(build_torchrun_cmd(aug_mult=1, epsilon=EPSILON, run_name="aug_mult_1_epochs_200", n_epochs=200))
    experiments.append(build_torchrun_cmd(aug_mult=1, epsilon=EPSILON, run_name="aug_mult_1_batch_2000", batch_size=2000))
    experiments.append(build_torchrun_cmd(aug_mult=1, epsilon=EPSILON, run_name="wideresnet", model_name="wideresnet"))
    
    script = f'''#!/bin/bash
#SBATCH --job-name=sweep_aug_mult
#SBATCH --output=sweep_aug_mult_%j.out
#SBATCH --error=sweep_aug_mult_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --time=24:00:00

# Generated by sweep_aug_mult_parallel.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

echo "Starting CIFAR10 aug_mult sweep"
echo "Testing aug_mult values: {AUG_MULT_VALUES}"

'''
    
    for run_name, args in experiments:
        script += f'''
echo "========================================"
echo "Running: {run_name}"
echo "========================================"

srun --ntasks=$SLURM_NNODES --nodes=$SLURM_NNODES bash -c '
       MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1);
       MASTER_PORT=29500;
       RANK=$SLURM_PROCID;
       torchrun --nnodes=$SLURM_NNODES --nproc_per_node={NPROC_PER_NODE} \\
         --rdzv_backend=c10d \\
         --rdzv_endpoint=${{MASTER_ADDR}}:${{MASTER_PORT}} \\
         parallel_audit_model.py \\
         {args}'

'''
    
    script += '''
echo "========================================"
echo "Sweep completed!"
echo "========================================"
'''
    
    return script


def run_experiment_local(aug_mult, epsilon=EPSILON, run_name=None, n_epochs=N_EPOCHS, 
                         batch_size=BATCH_SIZE, model_name=MODEL_NAME, max_grad_norm=MAX_GRAD_NORM):
    """Run parallel_audit_model.py locally using torchrun (single node)."""
    if run_name is None:
        run_name = f"aug_mult_{aug_mult}"
    out_folder = f"{OUT_DIR}/{run_name}"
    
    cmd = [
        sys.executable, "-m", "torch.distributed.run",
        "--nproc_per_node", str(NPROC_PER_NODE),
        "--standalone",
        "parallel_audit_model.py",
        "--data_name", "cifar10",
        "--model_name", model_name,
        "--aug_mult", str(aug_mult),
        "--n_reps", str(N_REPS),
        "--n_epochs", str(n_epochs),
        "--lr", str(LR),
        "--batch_size", str(batch_size),
        "--block_size", str(BLOCK_SIZE),
        "--seed", str(SEED),
        "--out", out_folder,
        "--fixed_init",
    ]
    
    if epsilon is not None:
        cmd.extend(["--epsilon", str(epsilon)])
        cmd.extend(["--delta", str(DELTA)])
        cmd.extend(["--max_grad_norm", str(max_grad_norm)])
    else:
        cmd.extend(["--max_grad_norm", "-1"])
    
    max_physical_batch_size = get_max_physical_batch_size(aug_mult)
    cmd.extend(["--max_physical_batch_size", str(max_physical_batch_size)])
    
    if FIT_WORLD_ONLY is not None:
        cmd.extend(["--fit_world_only", FIT_WORLD_ONLY])
    
    print(f"\n{'='*60}")
    print(f"Running experiment: {run_name}")
    print(f"Command: {' '.join(cmd)}")
    print(f"{'='*60}\n")
    
    result = subprocess.run(cmd)
    return result.returncode


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true", help="Run experiments locally instead of generating SLURM script")
    parser.add_argument("--output", type=str, default="sweep_aug_mult.slurm", help="Output SLURM script filename")
    args = parser.parse_args()
    
    if args.run:
        # Run locally
        print("CIFAR10 aug_mult Sweep (Parallel - Local)")
        print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        os.makedirs(OUT_DIR, exist_ok=True)
        results = {}
        
        if RUN_NON_PRIVATE:
            returncode = run_experiment_local(aug_mult=1, epsilon=None, run_name="non_private")
            results["non_private"] = "success" if returncode == 0 else f"failed (code {returncode})"
        
        for aug_mult in AUG_MULT_VALUES:
            returncode = run_experiment_local(aug_mult)
            results[f"aug_mult_{aug_mult}"] = "success" if returncode == 0 else f"failed (code {returncode})"
        
        returncode = run_experiment_local(aug_mult=1, epsilon=EPSILON, run_name="aug_mult_1_epochs_200", n_epochs=200)
        results["aug_mult_1_epochs_200"] = "success" if returncode == 0 else f"failed (code {returncode})"
        
        returncode = run_experiment_local(aug_mult=1, epsilon=EPSILON, run_name="aug_mult_1_batch_2000", batch_size=2000)
        results["aug_mult_1_batch_2000"] = "success" if returncode == 0 else f"failed (code {returncode})"
        
        returncode = run_experiment_local(aug_mult=1, epsilon=EPSILON, run_name="wideresnet", model_name="wideresnet")
        results["wideresnet"] = "success" if returncode == 0 else f"failed (code {returncode})"
        
        print(f"\n{'='*60}")
        print("SWEEP SUMMARY")
        print(f"{'='*60}")
        for name, status in results.items():
            print(f"  {name}: {status}")
        print(f"\nCompleted: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    else:
        # Generate SLURM script
        script = generate_slurm_script()
        
        with open(args.output, "w") as f:
            f.write(script)
        
        print(f"Generated SLURM script: {args.output}")
        print(f"Submit with: sbatch {args.output}")


if __name__ == "__main__":
    main()
